import { Platform, StyleSheet } from "react-native";
import { palette } from "../../theme/themes";

const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: palette.cream },
  appShell: {
    flex: 1,
    width: "100%",
    alignSelf: "center",
    backgroundColor: palette.cream,
    overflow: "hidden",
  },
  screenLayer: { flex: 1, zIndex: 1 },
  desktopMain: {
    flex: 1,
    minWidth: 0,
    position: "relative",
    overflow: "hidden",
  },
  desktopScreenLayer: {
    width: "100%",
    maxWidth: 1120,
    alignSelf: "center",
  },
  desktopSidebar: {
    width: 260,
    borderRightWidth: 1,
    paddingHorizontal: 20,
    paddingVertical: 24,
    zIndex: 4,
  },
  desktopBrand: {
    flexDirection: "row",
    alignItems: "center",
    gap: 11,
    marginBottom: 28,
  },
  desktopBrandIcon: {
    width: 44,
    height: 44,
    borderRadius: 15,
    alignItems: "center",
    justifyContent: "center",
  },
  desktopBrandName: {
    fontSize: 19,
    fontWeight: "900",
    letterSpacing: -0.4,
  },
  desktopBrandCaption: {
    fontSize: 7,
    fontWeight: "900",
    letterSpacing: 1.5,
    marginTop: 2,
  },
  desktopProfile: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderRadius: 18,
    padding: 12,
    marginBottom: 24,
  },
  desktopProfileText: { flex: 1, marginLeft: 10 },
  desktopProfileName: { fontSize: 13, fontWeight: "900" },
  desktopProfileCaption: { fontSize: 9, marginTop: 2 },
  desktopRefreshButton: {
    minHeight: 44,
    borderRadius: 14,
    borderWidth: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    marginBottom: 18,
    paddingHorizontal: 12,
  },
  desktopRefreshButtonDisabled: { opacity: 0.62 },
  desktopRefreshButtonText: { fontSize: 11, fontWeight: "800" },
  desktopNavigation: { gap: 7 },
  desktopNavItem: {
    minHeight: 52,
    flexDirection: "row",
    alignItems: "center",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "transparent",
    paddingHorizontal: 10,
  },
  desktopNavIcon: {
    width: 34,
    height: 34,
    borderRadius: 11,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 11,
  },
  desktopNavLabel: { fontSize: 12, fontWeight: "700" },
  desktopNavLabelActive: { fontWeight: "900" },
  desktopSidebarFooter: { marginTop: "auto", paddingHorizontal: 10 },
  desktopSidebarFooterTitle: { fontSize: 10, fontWeight: "800" },
  desktopSidebarFooterText: { fontSize: 8, marginTop: 3 },
  themeDecorations: {
    ...StyleSheet.absoluteFillObject,
    overflow: "hidden",
    pointerEvents: "none",
  },
  themeBubble: {
    position: "absolute",
    width: 112,
    height: 112,
    borderRadius: 56,
    opacity: 0.42,
  },
  themeBubbleTop: { right: 30, top: -46 },
  themeBubbleBottom: { left: -48, bottom: 80 },
  themeCornerIcon: {
    position: "absolute",
    right: 18,
    top: 92,
    transform: [{ rotate: "12deg" }],
  },
  themeCharacterTop: {
    position: "absolute",
    right: 56,
    top: 2,
    width: 82,
    height: 82,
    opacity: 0.9,
  },
  cinnamorollCharacterTop: { right: 50, width: 118 },
  themeCharacterBottom: {
    position: "absolute",
    left: -25,
    bottom: 72,
    width: 92,
    height: 92,
    opacity: 0.48,
    transform: [{ rotate: "-10deg" }],
  },
  cinnamorollCharacterBottom: { left: -22, width: 112 },
  scrollContent: {
    width: "100%",
    paddingHorizontal: 36,
    paddingTop: 28,
    paddingBottom: 70,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: Platform.OS === "android" ? 16 : 4,
    marginBottom: 24,
  },
  eyebrow: {
    fontSize: 10,
    letterSpacing: 1.8,
    color: palette.rose,
    fontWeight: "800",
    marginBottom: 5,
  },
  pageTitle: {
    fontSize: 29,
    letterSpacing: -0.7,
    color: palette.ink,
    fontWeight: "800",
  },
  addButton: {
    width: 44,
    height: 44,
    borderRadius: 15,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: palette.ink,
    shadowColor: palette.ink,
    shadowOpacity: 0.16,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 5 },
  },
  pressed: { opacity: 0.82, transform: [{ scale: 0.98 }] },
  heroCard: {
    minHeight: 225,
    borderRadius: 30,
    padding: 25,
    overflow: "hidden",
    shadowColor: palette.rose,
    shadowOpacity: 0.2,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 9 },
    marginBottom: 30,
  },
  heroDecorationOne: {
    position: "absolute",
    width: 180,
    height: 180,
    borderRadius: 90,
    backgroundColor: "rgba(255,255,255,0.09)",
    right: -58,
    top: -55,
  },
  heroDecorationTwo: {
    position: "absolute",
    width: 110,
    height: 110,
    borderRadius: 55,
    borderWidth: 22,
    borderColor: "rgba(255,255,255,0.07)",
    left: -40,
    bottom: -52,
  },
  heroKicker: {
    color: "rgba(255,255,255,0.75)",
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 1.5,
  },
  heroTitle: {
    color: palette.paper,
    fontSize: 27,
    lineHeight: 32,
    fontWeight: "800",
    letterSpacing: -0.5,
    marginTop: 12,
    maxWidth: "88%",
  },
  heroNote: {
    color: "rgba(255,255,255,0.8)",
    fontSize: 14,
    lineHeight: 20,
    marginTop: 8,
    maxWidth: "88%",
  },
  heroFooter: {
    marginTop: "auto",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  avatarStack: { flexDirection: "row" },
  avatar: {
    width: 35,
    height: 35,
    borderRadius: 18,
    borderWidth: 2,
    borderColor: palette.paper,
    alignItems: "center",
    justifyContent: "center",
  },
  avatarOverlap: { marginLeft: -9 },
  avatarText: { color: palette.ink, fontSize: 12, fontWeight: "800" },
  heroDate: {
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
    backgroundColor: "rgba(255,255,255,0.16)",
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  heroDateText: {
    color: palette.paper,
    fontSize: 10,
    letterSpacing: 0.8,
    fontWeight: "800",
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 4,
    marginBottom: 15,
  },
  sectionEyebrow: {
    color: palette.rose,
    fontSize: 9,
    fontWeight: "800",
    letterSpacing: 1.4,
    marginBottom: 3,
  },
  sectionTitle: {
    fontSize: 20,
    letterSpacing: -0.35,
    fontWeight: "800",
    color: palette.ink,
  },
  progressBadge: {
    backgroundColor: "#EFE6F4",
    paddingHorizontal: 11,
    paddingVertical: 7,
    borderRadius: 15,
  },
  progressText: { color: palette.lilac, fontSize: 11, fontWeight: "700" },
  statsRow: { flexDirection: "row", gap: 12, marginBottom: 28 },
  statCard: {
    flex: 1,
    borderRadius: 22,
    backgroundColor: palette.paper,
    padding: 17,
    borderWidth: 1,
    borderColor: palette.line,
  },
  statValue: {
    color: palette.ink,
    fontSize: 25,
    fontWeight: "800",
    marginTop: 14,
  },
  statLabel: { color: palette.muted, fontSize: 11, marginTop: 2 },
  linkText: { color: palette.rose, fontWeight: "700", fontSize: 12 },
  memoryCard: {
    flexDirection: "row",
    backgroundColor: palette.paper,
    borderRadius: 22,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: palette.line,
    marginBottom: 13,
  },
  memoryStripe: { width: 6 },
  memoryBody: { flex: 1, padding: 16 },
  memoryTop: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  memoryTopActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  memoryEditButton: {
    width: 30,
    height: 30,
    borderRadius: 10,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  categoryPill: {
    flexDirection: "row",
    gap: 5,
    alignItems: "center",
    paddingHorizontal: 9,
    paddingVertical: 5,
    borderRadius: 12,
  },
  categoryPillText: { fontSize: 10, fontWeight: "700" },
  dateText: { color: "#A0979D", fontSize: 9, fontWeight: "800", letterSpacing: 0.7 },
  memoryTitle: {
    color: palette.ink,
    fontSize: 16,
    fontWeight: "800",
    marginTop: 12,
  },
  memoryNote: {
    color: palette.muted,
    fontSize: 12,
    lineHeight: 17,
    marginTop: 5,
  },
  memoryPhotoButton: {
    width: "100%",
    height: 150,
    borderRadius: 15,
    marginTop: 13,
    overflow: "hidden",
    position: "relative",
  },
  memoryPhoto: { width: "100%", height: "100%" },
  memoryPhotoBadge: {
    position: "absolute",
    right: 9,
    bottom: 9,
    minHeight: 28,
    borderRadius: 14,
    paddingHorizontal: 10,
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    backgroundColor: "rgba(32,25,29,0.72)",
  },
  memoryPhotoBadgeText: {
    color: palette.paper,
    fontSize: 9,
    fontWeight: "800",
  },
  photoViewerOverlay: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: 28,
    backgroundColor: "rgba(24,19,22,0.84)",
  },
  photoViewerDismiss: { ...StyleSheet.absoluteFillObject },
  photoViewerCard: {
    width: "100%",
    maxWidth: 1100,
    height: "88%",
    borderRadius: 24,
    borderWidth: 1,
    overflow: "hidden",
    zIndex: 1,
  },
  photoViewerHeader: {
    minHeight: 62,
    borderBottomWidth: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingHorizontal: 18,
  },
  photoViewerTitle: { flex: 1, fontSize: 16, fontWeight: "900" },
  photoViewerClose: {
    width: 38,
    height: 38,
    borderRadius: 13,
    alignItems: "center",
    justifyContent: "center",
  },
  photoViewerImage: { flex: 1, width: "100%" },
  memoryFooter: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 14,
  },
  ratingRow: { flexDirection: "row", gap: 2 },
  memorySavedText: { color: palette.muted, fontSize: 10, fontWeight: "700" },
  introText: {
    color: palette.muted,
    fontSize: 14,
    lineHeight: 21,
    marginTop: -11,
    marginBottom: 22,
    maxWidth: 320,
  },
  collectionFilterToolbar: {
    minHeight: 58,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  collectionFilterHint: {
    color: palette.muted,
    fontSize: 9,
    marginTop: 3,
  },
  collectionFilterButton: {
    minWidth: 105,
    height: 43,
    borderRadius: 15,
    borderWidth: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
    paddingHorizontal: 13,
  },
  collectionFilterButtonText: { fontSize: 11, fontWeight: "800" },
  collectionFilterBadge: {
    minWidth: 19,
    height: 19,
    borderRadius: 10,
    backgroundColor: palette.paper,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 5,
  },
  collectionFilterBadgeText: { fontSize: 9, fontWeight: "900" },
  activeFilterList: { gap: 7, paddingBottom: 7 },
  activeFilterChip: {
    borderRadius: 13,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  activeFilterChipText: { fontSize: 9, fontWeight: "800" },
  resultCount: {
    color: "#9D9399",
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 1,
    textTransform: "uppercase",
  },
  memoryMonthGroup: { marginTop: 8 },
  memoryMonthDivider: {
    minHeight: 40,
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 10,
  },
  memoryMonthIcon: {
    width: 31,
    height: 31,
    borderRadius: 11,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 9,
  },
  memoryMonthTitle: {
    fontSize: 13,
    fontWeight: "900",
    letterSpacing: -0.1,
  },
  memoryMonthCount: {
    minWidth: 25,
    height: 22,
    borderRadius: 11,
    paddingHorizontal: 7,
    alignItems: "center",
    justifyContent: "center",
    marginLeft: 8,
  },
  memoryMonthCountText: { fontSize: 9, fontWeight: "900" },
  memoryMonthLine: {
    flex: 1,
    height: 1,
    marginLeft: 10,
  },
  emptyState: { alignItems: "center", paddingVertical: 55 },
  emptyTitle: { color: palette.ink, fontWeight: "800", fontSize: 17, marginTop: 14 },
  emptyText: { color: palette.muted, fontSize: 12, marginTop: 5 },
  monthCard: {
    backgroundColor: palette.ink,
    borderRadius: 26,
    padding: 22,
    marginBottom: 28,
  },
  monthTop: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  monthGoalContent: { flex: 1, paddingRight: 14 },
  monthLabel: {
    color: palette.paper,
    fontSize: 9,
    letterSpacing: 1.4,
    fontWeight: "800",
  },
  monthTitle: { color: palette.paper, fontSize: 18, fontWeight: "800", marginTop: 5 },
  monthProgress: { color: palette.paper, fontSize: 24, fontWeight: "800" },
  progressTrack: {
    height: 6,
    borderRadius: 3,
    backgroundColor: "rgba(255,255,255,0.15)",
    marginTop: 22,
    overflow: "hidden",
  },
  progressFill: { height: "100%", borderRadius: 3 },
  monthHint: {
    color: "rgba(255,255,255,0.55)",
    fontSize: 11,
    marginTop: 13,
  },
  plansCalendarCard: {
    borderRadius: 24,
    borderWidth: 1,
    padding: 15,
    marginBottom: 12,
  },
  plansCalendarHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 16,
  },
  plansCalendarNav: {
    width: 36,
    height: 36,
    borderRadius: 13,
    alignItems: "center",
    justifyContent: "center",
  },
  plansCalendarHeading: { flex: 1, alignItems: "center", paddingHorizontal: 8 },
  plansCalendarMonth: { fontSize: 15, fontWeight: "900" },
  plansCalendarSubtitle: { color: palette.muted, fontSize: 9, marginTop: 3 },
  plansCalendarGrid: { flexDirection: "row", flexWrap: "wrap" },
  plansCalendarWeekday: {
    width: "14.2857%",
    color: palette.muted,
    fontSize: 8,
    fontWeight: "900",
    textAlign: "center",
    marginBottom: 8,
  },
  plansCalendarDayCell: {
    width: "14.2857%",
    height: 48,
    alignItems: "center",
    justifyContent: "center",
  },
  plansCalendarDay: {
    width: 40,
    height: 42,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
  },
  plansCalendarDayText: { fontSize: 11, fontWeight: "800" },
  plansCalendarDayTextSelected: { color: palette.paper },
  plansCalendarCount: {
    position: "absolute",
    right: 2,
    bottom: 2,
    minWidth: 14,
    height: 14,
    borderRadius: 7,
    paddingHorizontal: 3,
    alignItems: "center",
    justifyContent: "center",
  },
  plansCalendarCountText: { fontSize: 7, fontWeight: "900" },
  dayAgenda: {
    borderRadius: 20,
    borderWidth: 1,
    padding: 15,
    marginBottom: 27,
  },
  dayAgendaHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  dayAgendaTitle: { fontSize: 14, fontWeight: "900" },
  dayAgendaSubtitle: { color: palette.muted, fontSize: 9, marginTop: 3 },
  todayBadge: {
    minHeight: 24,
    borderRadius: 12,
    paddingHorizontal: 9,
    alignItems: "center",
    justifyContent: "center",
  },
  todayBadgeText: { fontSize: 8, fontWeight: "900", letterSpacing: 0.7 },
  dayAgendaEmpty: {
    minHeight: 76,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginTop: 10,
    paddingHorizontal: 5,
  },
  dayAgendaEmptyText: {
    flex: 1,
    color: palette.muted,
    fontSize: 10,
    lineHeight: 15,
  },
  dayAgendaItem: {
    flexDirection: "row",
    alignItems: "flex-start",
    borderTopWidth: 1,
    paddingTop: 13,
    marginTop: 13,
  },
  dayAgendaCheck: {
    width: 26,
    height: 26,
    borderRadius: 9,
    borderWidth: 1.5,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 10,
  },
  dayAgendaContent: { flex: 1 },
  dayAgendaItemTitle: { fontSize: 12, fontWeight: "800" },
  dayAgendaItemNote: { color: palette.muted, fontSize: 9, marginTop: 3 },
  dayAgendaMeta: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 7,
  },
  dayAgendaType: { fontSize: 8, fontWeight: "800" },
  dayAgendaStatus: { fontSize: 8, fontWeight: "900", letterSpacing: 0.5 },
  planRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 17,
    borderBottomWidth: 1,
    borderBottomColor: palette.line,
  },
  bigCheck: {
    width: 29,
    height: 29,
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: "#D6CBD0",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 13,
  },
  planContent: { flex: 1 },
  planTitle: { color: palette.ink, fontSize: 14, fontWeight: "800" },
  planNote: { color: palette.muted, fontSize: 11, marginTop: 4, paddingRight: 10 },
  planIdeaBadge: {
    alignSelf: "flex-start",
    minHeight: 24,
    borderRadius: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 8,
    marginTop: 8,
  },
  planIdeaBadgeText: { fontSize: 9, fontWeight: "800" },
  planDateContainer: {
    minWidth: 72,
    alignItems: "flex-end",
    justifyContent: "center",
    gap: 4,
    marginLeft: 8,
  },
  planDate: {
    color: palette.rose,
    fontWeight: "800",
    fontSize: 9,
    textAlign: "right",
  },
  doneText: { textDecorationLine: "line-through", color: "#9B9297" },
  dashedButton: {
    height: 58,
    marginTop: 23,
    borderRadius: 18,
    borderWidth: 1.5,
    borderStyle: "dashed",
    borderColor: "#D8B8BA",
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 8,
  },
  dashedButtonText: { color: palette.rose, fontSize: 12, fontWeight: "700" },
  downloadHero: {
    minHeight: 236,
    borderRadius: 30,
    padding: 25,
    overflow: "hidden",
    shadowColor: palette.rose,
    shadowOpacity: 0.18,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 9 },
    marginBottom: 18,
  },
  downloadHeroIcon: {
    width: 54,
    height: 54,
    borderRadius: 18,
    backgroundColor: "rgba(255,255,255,0.18)",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 18,
  },
  downloadHeroKicker: {
    color: "rgba(255,255,255,0.72)",
    fontSize: 10,
    fontWeight: "900",
    letterSpacing: 1.5,
  },
  downloadHeroTitle: {
    color: palette.paper,
    fontSize: 27,
    lineHeight: 32,
    fontWeight: "900",
    letterSpacing: -0.5,
    marginTop: 8,
    maxWidth: 520,
  },
  downloadHeroText: {
    color: "rgba(255,255,255,0.82)",
    fontSize: 13,
    lineHeight: 20,
    marginTop: 9,
    maxWidth: 560,
  },
  downloadHeroButton: {
    alignSelf: "flex-start",
    minHeight: 40,
    borderRadius: 14,
    backgroundColor: palette.paper,
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
    paddingHorizontal: 14,
    marginTop: 18,
  },
  downloadHeroButtonText: { fontSize: 11, fontWeight: "900" },
  downloadPlatformGrid: {
    flexDirection: "row",
    gap: 12,
    marginBottom: 25,
  },
  downloadPlatformCard: {
    flex: 1,
    borderRadius: 22,
    borderWidth: 1,
    padding: 18,
    minHeight: 142,
  },
  downloadPlatformIcon: {
    width: 43,
    height: 43,
    borderRadius: 15,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 14,
  },
  downloadPlatformTitle: { fontSize: 15, fontWeight: "900" },
  downloadPlatformText: {
    fontSize: 11,
    lineHeight: 16,
    marginTop: 6,
  },
  downloadVersionCard: {
    borderRadius: 22,
    borderWidth: 1,
    padding: 17,
    marginBottom: 12,
  },
  downloadVersionTop: {
    flexDirection: "row",
    alignItems: "center",
  },
  downloadVersionIcon: {
    width: 39,
    height: 39,
    borderRadius: 13,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 11,
  },
  downloadVersionInfo: { flex: 1 },
  downloadVersionTitle: { fontSize: 14, fontWeight: "900" },
  downloadVersionMeta: { fontSize: 9, marginTop: 3 },
  downloadStatusBadge: {
    minHeight: 28,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 10,
  },
  downloadStatusText: { fontSize: 8, fontWeight: "900", letterSpacing: 0.5 },
  downloadVersionNotes: {
    fontSize: 11,
    lineHeight: 16,
    marginTop: 13,
  },
  downloadActionButton: {
    alignSelf: "flex-start",
    minHeight: 39,
    borderRadius: 13,
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
    paddingHorizontal: 13,
    marginTop: 14,
  },
  downloadActionDisabled: { opacity: 0.55 },
  downloadActionText: {
    color: palette.paper,
    fontSize: 10,
    fontWeight: "900",
  },
  downloadEmptyCard: {
    alignItems: "center",
    borderRadius: 24,
    borderWidth: 1,
    padding: 24,
    marginBottom: 30,
  },
  downloadEmptyIcon: {
    width: 48,
    height: 48,
    borderRadius: 17,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 13,
  },
  downloadEmptyTitle: { fontSize: 16, fontWeight: "900" },
  downloadEmptyText: {
    fontSize: 11,
    lineHeight: 17,
    textAlign: "center",
    maxWidth: 520,
    marginTop: 8,
  },
  downloadOutlineButton: {
    minHeight: 42,
    borderRadius: 14,
    borderWidth: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
    paddingHorizontal: 14,
    marginTop: 16,
  },
  downloadOutlineButtonText: { fontSize: 10, fontWeight: "900" },
  coupleCard: {
    alignItems: "center",
    backgroundColor: "#F2E8F4",
    borderRadius: 28,
    padding: 28,
  },
  largeAvatars: { flexDirection: "row", alignItems: "center" },
  largeAvatar: {
    width: 75,
    height: 75,
    borderRadius: 38,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 4,
    borderColor: palette.paper,
  },
  largeAvatarText: { color: palette.ink, fontSize: 24, fontWeight: "800" },
  heartConnector: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: palette.rose,
    alignItems: "center",
    justifyContent: "center",
    marginHorizontal: -7,
    zIndex: 2,
  },
  coupleQuote: {
    color: palette.ink,
    fontSize: 14,
    lineHeight: 21,
    fontWeight: "600",
    textAlign: "center",
    marginTop: 19,
    maxWidth: 280,
  },
  achievementGrid: { flexDirection: "row", gap: 10, marginTop: 14 },
  achievement: {
    flex: 1,
    alignItems: "center",
    backgroundColor: palette.paper,
    borderRadius: 18,
    paddingVertical: 16,
    borderWidth: 1,
    borderColor: palette.line,
  },
  achievementValue: { color: palette.ink, fontSize: 20, fontWeight: "800" },
  achievementLabel: { color: palette.muted, fontSize: 9, marginTop: 3 },
  menuRow: {
    minHeight: 65,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: palette.paper,
    borderRadius: 18,
    marginBottom: 9,
    paddingHorizontal: 13,
    borderWidth: 1,
    borderColor: palette.line,
  },
  menuIcon: {
    width: 38,
    height: 38,
    borderRadius: 13,
    backgroundColor: "#F9E9E8",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 11,
  },
  menuLabel: { flex: 1, color: palette.ink, fontSize: 13, fontWeight: "700" },
  menuDetail: { color: "#A2989E", fontSize: 10, marginRight: 7 },
  tabBar: {
    position: "absolute",
    zIndex: 3,
    left: 14,
    right: 14,
    bottom: Platform.OS === "ios" ? 10 : 12,
    height: 72,
    backgroundColor: "rgba(255,255,255,0.97)",
    borderRadius: 25,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-around",
    borderWidth: 1,
    borderColor: palette.line,
    shadowColor: palette.ink,
    shadowOpacity: 0.12,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 8 },
  },
  tabButton: { flex: 1, alignItems: "center", justifyContent: "center", gap: 4 },
  tabText: { color: "#9C9298", fontSize: 9, fontWeight: "700" },
  tabTextActive: { color: palette.rose },
  filterModalSheet: {
    backgroundColor: palette.cream,
    width: "92%",
    maxWidth: 980,
    borderRadius: 28,
    padding: 26,
    paddingBottom: 24,
    maxHeight: "90%",
  },
  filterModalContent: { paddingBottom: 12 },
  filterSectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 3,
    marginBottom: 11,
  },
  filterSectionIcon: {
    width: 36,
    height: 36,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 10,
  },
  filterSectionTitle: { fontSize: 13, fontWeight: "900" },
  filterSectionHint: { color: palette.muted, fontSize: 9, marginTop: 2 },
  filterOptionGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 7,
    marginBottom: 22,
  },
  filterOption: {
    minHeight: 45,
    flexBasis: 100,
    flexGrow: 1,
    borderRadius: 14,
    borderWidth: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
    paddingHorizontal: 10,
  },
  filterOptionText: { color: palette.muted, fontSize: 10, fontWeight: "700" },
  filterMonthList: { gap: 7, marginBottom: 22 },
  filterMonthOption: {
    minHeight: 47,
    borderRadius: 14,
    borderWidth: 1,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 13,
    gap: 9,
  },
  filterMonthText: {
    flex: 1,
    color: palette.muted,
    fontSize: 10,
    fontWeight: "700",
  },
  filterRatingList: { gap: 7 },
  filterRatingOption: {
    minHeight: 45,
    borderRadius: 14,
    borderWidth: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 13,
  },
  filterRatingStars: { flexDirection: "row", gap: 3 },
  filterRatingLabelRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  filterRatingLabel: {
    color: palette.muted,
    fontSize: 10,
    fontWeight: "700",
  },
  filterModalActions: {
    flexDirection: "row",
    gap: 9,
    paddingTop: 13,
    borderTopWidth: 1,
    borderTopColor: palette.line,
  },
  filterClearButton: {
    width: 90,
    height: 50,
    borderRadius: 16,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  filterClearText: { fontSize: 11, fontWeight: "800" },
  filterApplyButton: { flex: 1, borderRadius: 16, overflow: "hidden" },
  filterApplyGradient: {
    height: 50,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  filterApplyText: { color: palette.paper, fontSize: 11, fontWeight: "900" },
  modalOverlay: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(35,28,34,0.4)",
    padding: 24,
  },
  modalDismiss: { ...StyleSheet.absoluteFillObject },
  goalModalSheet: {
    backgroundColor: palette.cream,
    width: "92%",
    maxWidth: 720,
    borderRadius: 28,
    padding: 26,
    paddingBottom: 26,
  },
  goalModalIntro: {
    fontSize: 11,
    lineHeight: 17,
    marginTop: -6,
    marginBottom: 20,
  },
  goalDescriptionInput: {
    height: 104,
    paddingTop: 14,
    textAlignVertical: "top",
    marginBottom: 7,
  },
  modalSheet: {
    backgroundColor: palette.cream,
    width: "94%",
    maxWidth: 1040,
    borderRadius: 30,
    padding: 28,
    paddingBottom: 28,
    maxHeight: "92%",
  },
  modalHandle: {
    width: 42,
    height: 5,
    borderRadius: 3,
    backgroundColor: "#D9CED3",
    alignSelf: "center",
    marginBottom: 20,
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 23,
  },
  modalBody: { flexShrink: 1 },
  modalBodyContent: { paddingBottom: 2 },
  modalEyebrow: {
    color: palette.rose,
    fontSize: 9,
    letterSpacing: 1.4,
    fontWeight: "800",
  },
  modalTitle: { color: palette.ink, fontSize: 25, fontWeight: "800", marginTop: 3 },
  closeButton: {
    width: 38,
    height: 38,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: palette.paper,
  },
  inputLabel: {
    color: palette.ink,
    fontSize: 11,
    fontWeight: "800",
    marginBottom: 9,
    marginTop: 2,
  },
  categoryGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 7,
    marginBottom: 20,
  },
  categoryOption: {
    flexGrow: 1,
    flexBasis: 96,
    minHeight: 62,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: palette.line,
    backgroundColor: palette.paper,
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
  },
  categoryOptionText: { color: palette.muted, fontSize: 9, fontWeight: "700" },
  datePickerButton: {
    minHeight: 62,
    borderRadius: 16,
    borderWidth: 1,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    marginBottom: 16,
  },
  datePickerIcon: {
    width: 39,
    height: 39,
    borderRadius: 13,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 11,
  },
  datePickerText: { flex: 1 },
  datePickerValue: { fontSize: 12, fontWeight: "800" },
  datePickerHint: { color: palette.muted, fontSize: 9, marginTop: 3 },
  clearPlannedDateButton: {
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    marginTop: -7,
    marginBottom: 17,
    paddingVertical: 4,
  },
  clearPlannedDateText: { fontSize: 10, fontWeight: "800" },
  calendarCard: {
    borderRadius: 18,
    borderWidth: 1,
    padding: 12,
    marginTop: -7,
    marginBottom: 18,
  },
  calendarHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 10,
  },
  calendarNavButton: {
    width: 34,
    height: 34,
    alignItems: "center",
    justifyContent: "center",
  },
  calendarNavDisabled: { opacity: 0.45 },
  calendarMonth: { fontSize: 13, fontWeight: "800" },
  calendarGrid: { flexDirection: "row", flexWrap: "wrap" },
  calendarWeekday: {
    width: "14.2857%",
    color: palette.muted,
    fontSize: 9,
    fontWeight: "800",
    textAlign: "center",
    marginBottom: 6,
  },
  calendarDayCell: {
    width: "14.2857%",
    height: 35,
    alignItems: "center",
    justifyContent: "center",
  },
  calendarDay: {
    width: 30,
    height: 30,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  calendarDayText: { color: palette.ink, fontSize: 11, fontWeight: "700" },
  calendarDayTextSelected: { color: palette.paper },
  calendarDayTextDisabled: { color: "#D7CFCA" },
  ratingPicker: {
    borderRadius: 16,
    borderWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 13,
    marginBottom: 18,
  },
  ratingPickerStars: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  ratingStarButton: {
    width: 43,
    height: 39,
    alignItems: "center",
    justifyContent: "center",
  },
  ratingPickerFooter: {
    minHeight: 20,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 7,
  },
  ratingPickerText: { color: palette.muted, fontSize: 10, fontWeight: "700" },
  ratingClearText: { fontSize: 10, fontWeight: "800" },
  input: {
    height: 51,
    borderRadius: 15,
    backgroundColor: palette.paper,
    borderWidth: 1,
    borderColor: palette.line,
    paddingHorizontal: 15,
    color: palette.ink,
    fontSize: 13,
    marginBottom: 18,
  },
  textArea: { height: 78, paddingTop: 14, textAlignVertical: "top" },
  addPhotoButton: {
    minHeight: 72,
    borderRadius: 16,
    borderWidth: 1,
    borderStyle: "dashed",
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    marginBottom: 18,
  },
  addPhotoIcon: {
    width: 43,
    height: 43,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 11,
  },
  addPhotoText: { flex: 1, paddingRight: 8 },
  addPhotoTitle: { fontSize: 12, fontWeight: "800" },
  addPhotoHint: {
    color: palette.muted,
    fontSize: 9,
    lineHeight: 13,
    marginTop: 3,
  },
  photoPreviewCard: {
    borderRadius: 17,
    borderWidth: 1,
    overflow: "hidden",
    marginBottom: 18,
  },
  photoPreview: { width: "100%", height: 175 },
  photoPreviewActions: {
    flexDirection: "row",
    gap: 8,
    padding: 10,
  },
  photoActionButton: {
    flex: 1,
    minHeight: 39,
    borderRadius: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
  },
  photoActionText: { fontSize: 10, fontWeight: "800" },
  photoRemoveButton: {
    flex: 1,
    minHeight: 39,
    borderRadius: 12,
    backgroundColor: "#F9ECE9",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
  },
  photoRemoveText: { color: "#A96363", fontSize: 10, fontWeight: "800" },
  saveButton: { borderRadius: 17, overflow: "hidden", marginTop: 2 },
  saveGradient: {
    height: 54,
    flexDirection: "row",
    gap: 9,
    alignItems: "center",
    justifyContent: "center",
  },
  saveButtonText: { color: palette.paper, fontSize: 13, fontWeight: "800" },
  gateSafeArea: { flex: 1, backgroundColor: palette.cream },
  gateContainer: {
    flex: 1,
    width: "100%",
    alignSelf: "center",
    paddingHorizontal: 48,
    paddingVertical: 34,
  },
  gateBrand: { alignItems: "center", marginTop: 18 },
  gateLogo: {
    width: 54,
    height: 54,
    borderRadius: 19,
    backgroundColor: palette.rose,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: palette.rose,
    shadowOpacity: 0.25,
    shadowRadius: 13,
    shadowOffset: { width: 0, height: 7 },
  },
  gateBrandName: {
    color: palette.ink,
    fontSize: 24,
    letterSpacing: -0.5,
    fontWeight: "900",
    marginTop: 11,
  },
  gateBrandTag: {
    color: palette.rose,
    fontSize: 8,
    fontWeight: "800",
    letterSpacing: 2.2,
    marginTop: 3,
  },
  gateContent: {
    flex: 1,
    width: "100%",
    maxWidth: 760,
    alignSelf: "center",
    justifyContent: "center",
  },
  gateTitle: {
    color: palette.ink,
    fontSize: 28,
    fontWeight: "800",
    letterSpacing: -0.6,
    textAlign: "center",
  },
  gateSubtitle: {
    color: palette.muted,
    fontSize: 13,
    lineHeight: 20,
    textAlign: "center",
    alignSelf: "center",
    maxWidth: 480,
    marginTop: 9,
  },
  profileChoices: { flexDirection: "row", gap: 20, marginTop: 34 },
  profileChoice: {
    flex: 1,
    backgroundColor: "rgba(255,255,255,0.9)",
    borderRadius: 26,
    borderWidth: 1,
    borderColor: palette.line,
    minHeight: 230,
    paddingVertical: 30,
    alignItems: "center",
    shadowColor: palette.ink,
    shadowOpacity: 0.06,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 7 },
  },
  profileAvatar: {
    overflow: "hidden",
    borderColor: palette.paper,
    alignItems: "center",
    justifyContent: "center",
  },
  avatarImage: { width: "100%", height: "100%" },
  profileInitial: { color: palette.paper, fontWeight: "900" },
  profileChoiceName: {
    color: palette.ink,
    fontSize: 18,
    fontWeight: "800",
    marginTop: 14,
  },
  enterProfile: {
    flexDirection: "row",
    gap: 5,
    alignItems: "center",
    marginTop: 8,
  },
  enterProfileText: { color: palette.rose, fontSize: 11, fontWeight: "700" },
  gatePrivacy: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
  },
  gatePrivacyText: { color: palette.muted, fontSize: 10 },
  loadingScreen: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: palette.cream,
  },
  loadingText: {
    color: palette.ink,
    fontSize: 20,
    fontWeight: "800",
    marginTop: 13,
  },
  editProfileButton: {
    width: 44,
    height: 44,
    borderRadius: 15,
    backgroundColor: palette.paper,
    borderWidth: 1,
    borderColor: palette.line,
    alignItems: "center",
    justifyContent: "center",
  },
  profileHero: {
    alignItems: "center",
    backgroundColor: palette.paper,
    borderRadius: 28,
    padding: 24,
    borderWidth: 1,
    borderColor: palette.line,
  },
  photoBadge: {
    position: "absolute",
    right: 0,
    bottom: 1,
    width: 32,
    height: 32,
    borderRadius: 12,
    borderWidth: 3,
    borderColor: palette.paper,
    alignItems: "center",
    justifyContent: "center",
  },
  profileName: {
    color: palette.ink,
    fontSize: 23,
    fontWeight: "900",
    letterSpacing: -0.4,
    marginTop: 13,
  },
  profileBirth: { color: palette.muted, fontSize: 11, marginTop: 5 },
  profileBio: {
    color: palette.muted,
    fontSize: 12,
    lineHeight: 18,
    textAlign: "center",
    maxWidth: 300,
    marginTop: 13,
  },
  outlineProfileButton: {
    borderWidth: 1,
    borderRadius: 15,
    paddingHorizontal: 20,
    paddingVertical: 9,
    marginTop: 17,
  },
  outlineProfileButtonText: { fontSize: 11, fontWeight: "800" },
  profileStats: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: palette.paper,
    borderRadius: 21,
    borderWidth: 1,
    borderColor: palette.line,
    paddingVertical: 15,
    marginTop: 12,
  },
  profileStat: { flex: 1, alignItems: "center" },
  profileStatValue: { color: palette.ink, fontSize: 18, fontWeight: "800" },
  profileStatLabel: { color: palette.muted, fontSize: 9, marginTop: 2 },
  profileStatDivider: { width: 1, height: 29, backgroundColor: palette.line },
  settingsSectionTitle: {
    color: palette.ink,
    fontSize: 16,
    fontWeight: "800",
    marginTop: 25,
    marginBottom: 10,
  },
  settingsCard: {
    backgroundColor: palette.paper,
    borderRadius: 21,
    borderWidth: 1,
    borderColor: palette.line,
    paddingHorizontal: 14,
  },
  themeHint: {
    color: palette.muted,
    fontSize: 10,
    fontWeight: "700",
    marginTop: 15,
    marginBottom: 12,
  },
  themeOptions: {
    flexDirection: "row",
    flexWrap: "wrap",
    paddingBottom: 2,
  },
  themeOption: {
    alignItems: "center",
    width: "50%",
    marginBottom: 18,
  },
  themeSwatch: {
    width: 52,
    height: 52,
    borderRadius: 17,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    overflow: "hidden",
  },
  themeSwatchActive: {
    transform: [{ scale: 1.06 }],
  },
  themeSwatchCharacter: { width: 46, height: 46 },
  themeSwatchCheck: {
    position: "absolute",
    right: 1,
    bottom: 1,
    width: 17,
    height: 17,
    borderRadius: 9,
    backgroundColor: palette.ink,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1.5,
    borderColor: palette.paper,
  },
  themeName: { fontSize: 10, marginTop: 7 },
  settingRow: {
    minHeight: 73,
    flexDirection: "row",
    alignItems: "center",
  },
  actionSettingRow: {
    minHeight: 65,
    flexDirection: "row",
    alignItems: "center",
  },
  settingIcon: {
    width: 39,
    height: 39,
    borderRadius: 13,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 11,
  },
  settingText: { flex: 1, paddingRight: 8 },
  settingToggle: {
    width: 46,
    height: 28,
    borderRadius: 14,
    padding: 3,
    justifyContent: "center",
  },
  settingToggleThumb: {
    width: 22,
    height: 22,
    borderRadius: 11,
    shadowColor: palette.ink,
    shadowOpacity: 0.18,
    shadowRadius: 3,
    shadowOffset: { width: 0, height: 1 },
  },
  settingLabel: { color: palette.ink, fontSize: 12, fontWeight: "800" },
  settingDescription: {
    color: palette.muted,
    fontSize: 9,
    lineHeight: 13,
    marginTop: 3,
  },
  settingDivider: { height: 1, marginLeft: 50 },
  notificationPermissionNotice: {
    flexDirection: "row",
    gap: 9,
    marginHorizontal: 13,
    marginBottom: 12,
    padding: 12,
    borderWidth: 1,
    borderRadius: 14,
  },
  notificationPermissionText: { flex: 1, alignItems: "flex-start" },
  notificationPermissionMessage: { fontSize: 10, lineHeight: 15 },
  notificationPermissionButton: {
    minHeight: 32,
    justifyContent: "center",
    borderRadius: 11,
    marginTop: 9,
    paddingHorizontal: 12,
  },
  notificationPermissionButtonText: {
    color: palette.paper,
    fontSize: 9,
    fontWeight: "800",
  },
  notificationPermissionDisabled: { opacity: 0.6 },
  disclosurePanel: { overflow: "hidden" },
  disclosureBox: {
    borderRadius: 14,
    padding: 14,
    marginBottom: 13,
  },
  aboutText: { color: palette.muted, fontSize: 11, lineHeight: 17 },
  aboutSignature: { fontSize: 10, fontWeight: "800", marginTop: 8 },
  privacyIntro: { fontSize: 10, lineHeight: 16, marginBottom: 4 },
  privacySection: { marginTop: 11 },
  privacyTitle: { fontSize: 10, fontWeight: "900" },
  privacyText: { fontSize: 9, lineHeight: 14, marginTop: 3 },
  privacyDocumentHint: { fontSize: 9, fontWeight: "800", marginTop: 13 },
  switchProfileButton: {
    height: 53,
    borderRadius: 17,
    borderWidth: 1,
    borderColor: "#E4C4C6",
    flexDirection: "row",
    gap: 8,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 24,
  },
  switchProfileText: { color: palette.rose, fontSize: 12, fontWeight: "800" },
  editModalPage: { flex: 1, backgroundColor: palette.cream },
  fullModalHeader: {
    height: 67,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    borderBottomWidth: 1,
    borderBottomColor: palette.line,
  },
  fullModalTitle: { color: palette.ink, fontSize: 16, fontWeight: "800" },
  fullModalSave: { fontSize: 13, fontWeight: "800" },
  editProfileContent: { padding: 22, paddingBottom: 50 },
  editPhotoArea: { alignItems: "center", marginBottom: 28 },
  editPhotoBadge: {
    position: "absolute",
    top: 79,
    marginLeft: 77,
    width: 35,
    height: 35,
    borderRadius: 13,
    borderWidth: 3,
    borderColor: palette.cream,
    alignItems: "center",
    justifyContent: "center",
  },
  changePhotoText: { fontSize: 11, fontWeight: "800", marginTop: 11 },
  profileBioInput: { height: 112, paddingTop: 14, textAlignVertical: "top" },
  characterCount: {
    color: palette.muted,
    fontSize: 9,
    textAlign: "right",
    marginTop: -13,
  },
});


export default styles;
